### ISSUE TITLE
`ff.FILINFO_fsize(fno)` seems to return a signed integer

### ISSUE THREAD

**Issue by acheronfail** [irori/js-fatfs#4]
I've noticed that for files that are `2147483648` bytes or greater, calling `ff.FILINFO_fsize(fno)` results in negative values.
I believe this is because the underlying API may be returning a signed 32bit integer rather than an unsigned 32bit integer?

I currently have this as a workaround which ensures they're unsigned (and the correct size):

```js
const size = ff.FILINFO_fsize(fno) >>> 0;
```

I had a quick look at the code, and is it [this part](https://github.com/irori/js-fatfs/blob/main/src/binding.c#L49) which is responsible for that? I'm not sure where the conversion should take place, but I feel like it shouldn't be return signed integers?

**Comment by irori** [comment]
The problem here is that there is no distinction between signed and unsigned in WebAssembly's function return types; when such a function is called from JavaScript, the result is interpreted as a signed integer.

We have Wasm wrapper functions in [post.js](https://github.com/irori/js-fatfs/blob/main/src/post.js) where we can convert the result to unsigned.

**Comment by irori** [comment]
Fixed in v0.2.1.
